-- Generated SQL INSERT statements for regex table from validationRule.php
-- Mapping: key->name, trans_arg->associated_kv, regex->pattern, lang=1, description=NULL

INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isName', '/^[a-zA-Z- ÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÒÓÔÕÖÙÚÛÜÝàáâãäåçèéêëìíîïðòóôõöùúûüýÿ]{2,300}$/', 1, 'validation.isName', NULL, CURRENT_TIMESTAMP, NULL);
INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isCity', '/^.{2,300}$/', 1, 'validation.isCity', NULL, CURRENT_TIMESTAMP, NULL);
INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isAddress', '/^.{2,300}$/', 1, 'validation.isAddress', NULL, CURRENT_TIMESTAMP, NULL);
INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isEstablishment', '/^[a-zA-Z0-9- ''ÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÒÓÔÕÖÙÚÛÜÝàáâãäåçèéêëìíîïðòóôõöùúûüýÿ<>%&]{2,300}$/', 1, 'validation.isEstablishment', NULL, CURRENT_TIMESTAMP, NULL);
INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isInteger', '/^[0-9]+$/', 1, 'validation.isInteger', NULL, CURRENT_TIMESTAMP, NULL);
INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isPhone', '/^(\+(9[976]\d|8[987530]\d|6[987]\d|5[90]\d|42\d|3[875]\d|2[98654321]\d|9[8543210]|8[6421]|6[6543210]|5[87654321]|4[987654310]|3[9643210]|2[70]|7|1)\d{1,14})?$/', 1, 'validation.isPhone', NULL, CURRENT_TIMESTAMP, NULL);
INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isZipcode', '/^[0-9]{5}$/', 1, 'validation.isZipcode', NULL, CURRENT_TIMESTAMP, NULL);
INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isEmail', '/^([a-zA-Z0-9\+_\-]+)(\.[a-zA-Z0-9\+_\-]+)*@([a-zA-Z0-9\-]+\.)+[a-zA-Z]{2,6}$/', 1, 'validation.isEmail', NULL, CURRENT_TIMESTAMP, NULL);
INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isKeyword', '/^[[a-zA-Z0-9 -_\/ÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÒÓÔÕÖÙÚÛÜÝàáâãäåçèéêëìíîïðòóôõöùúûüýÿ]{2,150}$/u', 1, 'validation.isKeyword', NULL, CURRENT_TIMESTAMP, NULL);
INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isLocation', '/^[[a-zA-Z0-9 ,\._\/ÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÒÓÔÕÖÙÚÛÜÝàáâãäåçèéêëìíîïðòóôõöùúûüýÿ-]{2,150}$/u', 1, 'validation.isLocation', NULL, CURRENT_TIMESTAMP, NULL);
INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isPseudo', '/^([a-zA-Z0-9-_]{2,30})|([a-zA-Z0-9\+_\-]+)(\.[a-zA-Z0-9\+_\-]+)*@([a-zA-Z0-9\-]+\.)+[a-zA-Z]{2,6}$/u', 1, 'validation.isPseudo', NULL, CURRENT_TIMESTAMP, NULL);
INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isCivility', '/^[1-2]$/', 1, 'validation.isCivility', NULL, CURRENT_TIMESTAMP, NULL);
INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isPassword', '/^[a-zA-Z[0-9\.\/\)\(€§\-_!,;:=+''"#&@ÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÒÓÔÕÖÙÚÛÜÝàáâãäåçèéêëìíîïðòóôõöùúûüýÿ]{8,16}$/', 1, 'validation.password', NULL, CURRENT_TIMESTAMP, NULL);
INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isDate', '/^(((19)(\d{2})|(20)([01])(\d{1}))-(0?[1-9]|1?[012])-(([012])([0-9])|(3[01])))|((([012])([0-9])|(3[01]))-(0?[1-9]|1?[012])-((19)(\d{2})|(20)([01])(\d{1})))$/', 1, 'validation.isDate', NULL, CURRENT_TIMESTAMP, NULL);
INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isCard', '/^([0-9a-zA-Z]{8}|[0-9a-zA-Z]{13})$/', 1, 'validation.isCard', NULL, CURRENT_TIMESTAMP, NULL);
INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isOauthId', '/^[0-9a-zA-Z]{8,45}$/', 1, 'validation.isOauthId', NULL, CURRENT_TIMESTAMP, NULL);
INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isOptin', '/^[0-1]{1}$/i', 1, 'validation.isOptin', NULL, CURRENT_TIMESTAMP, NULL);
INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isMessage', '/^.{30,400}$/m', 1, 'validation.isMessage', NULL, CURRENT_TIMESTAMP, NULL);
INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isUuid', '/^[a-zA-Z-0-9]{1,400}$/', 1, 'validation.isUuid', NULL, CURRENT_TIMESTAMP, NULL);
INSERT INTO regex (name, pattern, lang, associated_kv, description, created_at, updated_at) VALUES ('isOtherid', '/^[0-9a-zA-Z\-_ ]{4,256}$/', 1, 'validation.isOtherid', NULL, CURRENT_TIMESTAMP, NULL);